version: '3'

services:
  client:
    build: ./client
    ports:
      - "5000:5000"
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
