version: "3.9"

services:
  frontend:
    build: client
    ports:
      - "5000:5000"
    volumes:
      - ./client:/app
    depends_on:
      - backend

  backend:
    build: server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app


  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  mongo-data: